# Generated by Django 4.1.7 on 2023-03-28 10:50

from django.db import migrations

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Company = apps.get_model('api', 'Company')
    Config = apps.get_model('api', 'Configuration')

    # Add initial data for the company model
    company_1 = Company(name="Company 1")
    company_1.save()

    company_2 = Company(name="Company 2", )
    company_2.save()

    # Add initial data for the config model
    config_1 = Config(company=company_1, version=1, malicious_words=["word1", "word2"])
    config_1.save()

    config_2 = Config(company=company_2, version=1, malicious_words=["word3", "word4"])
    config_2.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
